# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('isselect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Generate_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=256)),
                ('orderStatus', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imgsrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('discribe', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='0', max_length=20)),
                ('pPirice', models.CharField(default='0', max_length=20)),
                ('sale', models.CharField(default='0', max_length=20)),
                ('person', models.CharField(default='0', max_length=10)),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsNum', models.IntegerField()),
                ('isselect', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Imgsrc')),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Generate_order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='昵称[]', max_length=40)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('token', models.CharField(max_length=80)),
                ('imghead', models.CharField(default='default.jpg', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='generate_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Imgsrc'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
