# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imghead',
            field=models.CharField(default='default.jpg', max_length=256),
        ),
    ]
