# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='昵称[]', max_length=40),
        ),
    ]
