# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='generate_order',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
