# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_imghead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgsrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('discribe', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='￥0', max_length=20)),
                ('pPirice', models.CharField(default='￥0', max_length=20)),
                ('sale', models.CharField(default='0', max_length=20)),
                ('person', models.CharField(default='0', max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
